### ISSUE TITLE
Integrate Login with new recover account API.

### ISSUE THREAD

**Issue by germanferrero** [LibreRouterOrg/soporteremoto-dashboard#36]
Ask the user if she is sure about having typed the seed phrase correctly, when there is no data about the recovered identity. If the answer is yer, continue to home. Otherwise let her type again.

**Comment by gmarcos87** [comment]
How cute it works! :)
I would make two changes:
* That it is a textbox instead of an input password type, the text string is long and it is useful to see it complete to avoid errors.
* If you detect a user with that key hide the textbox and show only the welcome greeting. It is impossible that mistaking the phrase generates the key of another user.

**Comment by germanferrero** [comment]
Merged with suggested changes :)
